name: NMBaltazarCV

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Buld
    runs-on: ubuntu-latest
    steps:
    - name: Check repository
      uses: actions/checkout@main
    - name: Archive product artifact
      uses: actions/upload-artifact@main
      with:
        name: publicweb
        path: publicweb
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Download artifact
        uses: actions/download-artifact@main
        with:
          name: publicweb
          path: publicweb
      - name: Deplot to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
